# Generated by Django 3.2.13 on 2022-10-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0002_auto_20221005_0955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chain',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chain',
            new_name='update',
        ),
        migrations.AddField(
            model_name='message',
            name='parent',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
