# Generated by Django 3.2.13 on 2022-10-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0005_ngwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngwords',
            name='text',
            field=models.TextField(),
        ),
    ]
